# Generated by Django 5.1.6 on 2025-03-01 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='is_lost',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='api.pet')),
            ],
        ),
    ]
