# Generated by Django 5.1.6 on 2026-01-16 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pregeneratedqr',
            options={'ordering': ['-created_at'], 'verbose_name': 'QR Pre-generado', 'verbose_name_plural': 'QRs Pre-generados'},
        ),
        migrations.AddField(
            model_name='pet',
            name='qr_code_svg',
            field=models.FileField(blank=True, null=True, upload_to='qr_codes_svg/'),
        ),
        migrations.AddField(
            model_name='pregeneratedqr',
            name='qr_code_svg',
            field=models.FileField(blank=True, null=True, upload_to='pre_generated_qr_codes_svg/'),
        ),
    ]
