# Generated by Django 5.1.6 on 2025-03-25 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='allergies',
            field=models.TextField(blank=True, help_text='Alergias conocidas de la mascota', null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='blood_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Macho'), ('F', 'Hembra')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='is_sterilized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pet',
            name='medical_conditions',
            field=models.TextField(blank=True, help_text='Condiciones médicas crónicas', null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='microchip_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='sterilization_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='vet_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='vet_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='vet_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('treatment', models.TextField()),
                ('vet_name', models.CharField(max_length=100)),
                ('attachments', models.FileField(blank=True, upload_to='medical_records/')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='api.pet')),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_administered', models.DateField()),
                ('date_next', models.DateField()),
                ('vet_name', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccines', to='api.pet')),
            ],
        ),
    ]
