# Generated by Django 5.1.6 on 2025-03-25 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pet_allergies_pet_birth_date_pet_blood_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccine',
            name='pet',
        ),
        migrations.AlterField(
            model_name='pet',
            name='allergies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Macho'), ('F', 'Hembra')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='medical_conditions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='MedicalRecord',
        ),
        migrations.DeleteModel(
            name='Vaccine',
        ),
    ]
