# Generated by Django 5.1.6 on 2025-06-03 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20250603_0036'),
        ('api', '0003_add_pregeneratedqr'),
    ]

    operations = [
    ]
