# Generated by Django 5.1.6 on 2025-03-27 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_pointtransaction_reward_userpoints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='claimed_at',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='claimed_by',
        ),
        migrations.RemoveField(
            model_name='userpoints',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userpoints',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='reward',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reward',
            name='pet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reward', to='api.pet'),
        ),
        migrations.AlterField(
            model_name='userpoints',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
