# Generated by Django 5.1.6 on 2025-03-27 23:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_reward_claimed_at_remove_reward_claimed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='deviceregistration',
            name='unique_registration',
        ),
        migrations.RemoveIndex(
            model_name='deviceregistration',
            name='reg_id_idx',
        ),
        migrations.AlterUniqueTogether(
            name='deviceregistration',
            unique_together={('user', 'registration_id')},
        ),
    ]
