"""
Django settings for pet_qr project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from decouple import config
import os
from dotenv import load_dotenv
import dj_database_url

# Load environment variables from .env
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = [
    'collarmascotar.onrender.com',
    'collarmascotar.vercel.app',
    'www.encuentrameqr.com',
    'encuentrameqr.com',
    'localhost',
    '127.0.0.1',
]

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASE_URL = config('DATABASE_URL', default=None)

if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=0,  # Importante: Transaction Pooler no soporta conexiones persistentes
            conn_health_checks=True,
        )
    }
    # Configuración específica para Transaction Pooler de Supabase
    DATABASES['default']['OPTIONS'] = {
        'connect_timeout': 10,
        'sslmode': 'require',
    }
    # IMPORTANTE: Deshabilitar server-side cursors para Transaction Pooler
    DATABASES['default']['DISABLE_SERVER_SIDE_CURSORS'] = True
else:
    # Opción 2: Configuración manual con variables de entorno individuales
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('SUPABASE_DB_NAME', default='postgres'),
            'USER': config('SUPABASE_DB_USER', default='postgres'),
            'PASSWORD': config('SUPABASE_DB_PASSWORD', default=''),
            'HOST': config('SUPABASE_DB_HOST', default=''),
            'PORT': config('SUPABASE_DB_PORT', default='6543'),
            'OPTIONS': {
                'connect_timeout': 10,
                'sslmode': 'require',
            },
            'CONN_MAX_AGE': 0,  # Sin pooling de conexiones
            'DISABLE_SERVER_SIDE_CURSORS': True,
        }
    }

# Configuración de Supabase para uso con el cliente de Supabase (opcional)
SUPABASE_URL = config('SUPABASE_URL', default='')
SUPABASE_SERVICE_ROLE_KEY = config('SUPABASE_SERVICE_ROLE_KEY', default='')
SUPABASE_ANON_KEY = config('SUPABASE_ANON_KEY', default='')


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Solo incluir en STATICFILES_DIRS si existe la carpeta 'static'
STATICFILES_DIRS = []
static_dir = os.path.join(BASE_DIR, 'static')
if os.path.exists(static_dir):
    STATICFILES_DIRS.append(static_dir)

# Configuración de Whitenoise
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files
MEDIA_URL = '/media/'
# Usar directorio dentro del proyecto para evitar problemas de permisos
MEDIA_ROOT = BASE_DIR / 'media'

# Asegurar que el directorio de media y sus subdirectorios existan
try:
    os.makedirs(str(MEDIA_ROOT), exist_ok=True)
    # Crear subdirectorios necesarios
    subdirs = [
        'pre_generated_qr_codes',
        'pre_generated_qr_codes_svg',
        'qr_codes',
        'qr_codes_svg',
        'pet_photos',
        'lost_posters',
    ]
    for subdir in subdirs:
        subdir_path = MEDIA_ROOT / subdir
        os.makedirs(str(subdir_path), exist_ok=True)
except Exception as e:
    # Log del error pero continuar sin interrumpir
    import logging
    logger = logging.getLogger(__name__)
    logger.warning(f"No se pudo crear el directorio de media: {str(e)}")

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Configuración de CORS
# IMPORTANTE: No permitir todos los orígenes en producción
CORS_ALLOW_ALL_ORIGINS = False

CORS_ALLOWED_ORIGINS = [
    "https://collarmascotar.onrender.com",
    "https://www.encuentrameqr.com",
    "https://encuentrameqr.com",
    "https://collarmascotar.vercel.app",
]

# Solo para desarrollo local
if DEBUG:
    CORS_ALLOWED_ORIGINS += [
        "http://localhost:3000",
        "http://localhost:5173",
        "http://localhost:8000",
        "http://127.0.0.1:3000",
        "http://127.0.0.1:5173",
        "http://127.0.0.1:8000",
    ]

# Configuración adicional de CORS
CORS_ALLOW_CREDENTIALS = True
CORS_PREFLIGHT_MAX_AGE = 86400  
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-csrf-token',
    'cache-control',
]

# Exponer headers adicionales si es necesario
CORS_EXPOSE_HEADERS = [
    'content-type',
    'authorization',
]

# Configuración adicional para asegurar que CORS funcione correctamente
# Permitir todos los subdominios de encuentrameqr.com
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.*\.encuentrameqr\.com$",
]

# Asegurar que el middleware procese las requests OPTIONS (preflight)
CORS_URLS_REGEX = r'^/api/.*$'


# Configuración de REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
}


# Configuración de Email
# Usa SMTP para enviar emails reales
# Si EMAIL_USE_CONSOLE está en True, usa el backend de consola (solo para desarrollo)
USE_CONSOLE_EMAIL = config('EMAIL_USE_CONSOLE', default=False, cast=bool)

if USE_CONSOLE_EMAIL:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@encuentrameqr.com')
    print("⚠️  MODO CONSOLA: Los emails se mostrarán en la consola, no se enviarán realmente.")
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
    EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
    EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=False, cast=bool)
    EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
    EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
    EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
    DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default=EMAIL_HOST_USER)
    
    # Validar que las credenciales estén configuradas
    if not EMAIL_HOST_USER or not EMAIL_HOST_PASSWORD:
        print("⚠️  ADVERTENCIA: EMAIL_HOST_USER o EMAIL_HOST_PASSWORD no están configurados.")
        print("⚠️  Los emails no se podrán enviar. Configura estas variables en tu archivo .env")
    else:
        print("✓  Configuración de email SMTP cargada correctamente.")


# Configuración de Firebase Admin SDK
FIREBASE_CREDENTIALS_PATH = BASE_DIR / 'credentials' / 'firebase-adminsdk.json'


# Configuración para Web Push
WEBPUSH_SETTINGS = {
    "VAPID_PUBLIC_KEY": "BGv-Zb95k8vUG0_p4JHfQoXouhg2PwRP97C2mTWC2jei4zrkP2k48Ui1xYNoSSvfbdcubaCo8q4DALd3kjzABc0",
    "VAPID_PRIVATE_KEY": "514n-moA8np5wm5HVfhtx3ESytwVqozEkCI1WGqCBNs",
    "VAPID_ADMIN_EMAIL": "janomaciel1@gmail.com"
}


# URLs de la aplicación
REACT_APP_API_URL = config('API_URL', default='http://localhost:8000/api')
API_URL = config('API_URL')
FRONTEND_URL = config('FRONTEND_URL', default='http://localhost:3000')


# Configuración de seguridad para producción
if not DEBUG:
    # CSRF Protection - IMPORTANTE: Debe incluir todos los orígenes permitidos
    CSRF_TRUSTED_ORIGINS = [
        "https://www.encuentrameqr.com",
        "https://encuentrameqr.com",
        "https://collarmascotar.onrender.com",
        "https://collarmascotar.vercel.app",
    ]
    
    # Security Headers
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Configuración adicional de cookies
    SESSION_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SAMESITE = 'Lax'
else:
    # En desarrollo, también configurar CSRF_TRUSTED_ORIGINS
    CSRF_TRUSTED_ORIGINS = [
        "http://localhost:3000",
        "http://localhost:5173",
        "http://localhost:8000",
        "http://127.0.0.1:3000",
        "http://127.0.0.1:5173",
        "http://127.0.0.1:8000",
    ]

# Configuración de Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'api': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}