"""
Django settings for pet_qr project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from decouple import config
import os
from dotenv import load_dotenv
import dj_database_url

# Load environment variables from .env
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = [
    'collarmascotar.onrender.com',
    'collarmascotar.vercel.app', 
    'localhost', 
    '127.0.0.1',
    'api.whatsapp.com',
    'web.whatsapp.com',
    'wa.me',
    '*'
]

                


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'api',
]



ROOT_URLCONF = 'config.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASE_URL = config('DATABASE_URL', default=None)

if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=0,  # Importante: Transaction Pooler no soporta conexiones persistentes
            conn_health_checks=True,
        )
    }
    # Configuración específica para Transaction Pooler de Supabase
    DATABASES['default']['OPTIONS'] = {
        'connect_timeout': 10,
        'sslmode': 'require',
    }
    # IMPORTANTE: Deshabilitar server-side cursors para Transaction Pooler
    DATABASES['default']['DISABLE_SERVER_SIDE_CURSORS'] = True
else:
    # Opción 2: Configuración manual con variables de entorno individuales
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('SUPABASE_DB_NAME', default='postgres'),
            'USER': config('SUPABASE_DB_USER', default='postgres'),
            'PASSWORD': config('SUPABASE_DB_PASSWORD', default=''),
            'HOST': config('SUPABASE_DB_HOST', default=''),
            'PORT': config('SUPABASE_DB_PORT', default='6543'),
            'OPTIONS': {
                'connect_timeout': 10,
                'sslmode': 'require',
            },
            'CONN_MAX_AGE': 0,  # Sin pooling de conexiones
            'DISABLE_SERVER_SIDE_CURSORS': True,
        }
    }
# Configuración de Supabase para uso con el cliente de Supabase (opcional)
SUPABASE_URL = config('SUPABASE_URL', default='')
SUPABASE_SERVICE_ROLE_KEY = config('SUPABASE_SERVICE_ROLE_KEY', default='')
SUPABASE_ANON_KEY = config('SUPABASE_ANON_KEY', default='')



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Solo incluir en STATICFILES_DIRS si existe la carpeta 'static'
STATICFILES_DIRS = []
static_dir = os.path.join(BASE_DIR, 'static')
if os.path.exists(static_dir):
    STATICFILES_DIRS.append(static_dir)

# Configuración de Whitenoise
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
SECURE_CONTENT_TYPE_NOSNIFF = True

# Media files
MEDIA_URL = '/media/'
if os.environ.get('RENDER'):
    MEDIA_ROOT = '/var/media'
else:
    MEDIA_ROOT = BASE_DIR / 'media'

# Asegurar que el directorio de media exista
try:
    os.makedirs(str(MEDIA_ROOT), exist_ok=True)
except Exception:
    # En entornos restringidos puede fallar la creación; continuar sin interrumpir
    pass

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuración para desarrollo
CORS_ALLOW_ALL_ORIGINS = True  # En producción, especificar orígenes

# Configuración de REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',  # Cambiado de IsAuthenticated a AllowAny
    ],
}

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Cambia según tu proveedor
EMAIL_PORT = 587
EMAIL_USE_SSL=False
EMAIL_USE_TLS=True
EMAIL_HOST_USER = 'janomaciel1@gmail.com'  # Tu email
EMAIL_HOST_PASSWORD = 'hcfmtsyiqpntlrkp'  # Contraseña o contraseña de aplicación
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


# Configuración de Firebase Admin SDK
FIREBASE_CREDENTIALS_PATH = BASE_DIR / 'credentials' / 'firebase-adminsdk.json'

# Configuración para Web Push
WEBPUSH_SETTINGS = {
    "VAPID_PUBLIC_KEY": "BGv-Zb95k8vUG0_p4JHfQoXouhg2PwRP97C2mTWC2jei4zrkP2k48Ui1xYNoSSvfbdcubaCo8q4DALd3kjzABc0",
    "VAPID_PRIVATE_KEY": "514n-moA8np5wm5HVfhtx3ESytwVqozEkCI1WGqCBNs",
    "VAPID_ADMIN_EMAIL": "janomaciel1@gmail.com"
}

REACT_APP_API_URL = config('API_URL', default='http://localhost:8000/api')

CORS_ALLOWED_ORIGINS = [
    "https://collarmascotar.onrender.com",
    "https://www.encuentrameqr.com",
    "https://encuentrameqr.com",
    "http://localhost:3000",
    "https://collarmascotar.vercel.app",
    "http://localhost:8000",
    "https://api.whatsapp.com",
    "https://web.whatsapp.com",
    "https://wa.me"
    
]

#CORS_ALLOW_CREDENTIALS = True

API_URL=config('API_URL')
FRONTEND_URL=config('FRONTEND_URL')


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
